apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web-odoo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8069
  selector:
    app: web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odooconfig
  labels:
    app: odooconfig
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odooaddons
  labels:
    app: odooaddons
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoolib
  labels:
    app: odoolib
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
